// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEyeWRIlcXeKbSD0c5pmNmpz6d5YSdP7k',
    appId: '1:471359135011:web:bec127c914172643f4c096',
    messagingSenderId: '471359135011',
    projectId: 'spotfinder-59f59',
    authDomain: 'spotfinder-59f59.firebaseapp.com',
    storageBucket: 'spotfinder-59f59.appspot.com',
    measurementId: 'G-MC262H6QPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7oqQ8dvSIl8tJa7GJQQeLcF6OHLcE9s',
    appId: '1:471359135011:android:70fd96246a0bd594f4c096',
    messagingSenderId: '471359135011',
    projectId: 'spotfinder-59f59',
    storageBucket: 'spotfinder-59f59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wm6XW33dakGiN7WoVvhDs0Zuj8qNiBQ',
    appId: '1:471359135011:ios:6cf52e49b1b3900df4c096',
    messagingSenderId: '471359135011',
    projectId: 'spotfinder-59f59',
    storageBucket: 'spotfinder-59f59.appspot.com',
    iosClientId: '471359135011-uhp47cl6qnu97n9gh7976pagojb4psg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5wm6XW33dakGiN7WoVvhDs0Zuj8qNiBQ',
    appId: '1:471359135011:ios:6cf52e49b1b3900df4c096',
    messagingSenderId: '471359135011',
    projectId: 'spotfinder-59f59',
    storageBucket: 'spotfinder-59f59.appspot.com',
    iosClientId: '471359135011-uhp47cl6qnu97n9gh7976pagojb4psg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotfinder',
  );
}
